language: elixir
sudo: false
otp_release:
  - 20.0
elixir:
  - 1.5.0
env:
  global:
    # Follow other language's environment
    # e.g.) `RACK_ENV=test` has been setted as Default Environment Variables
    # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
before_install:
  # https://docs.travis-ci.com/user/encrypting-files/
  # Decrypt the file about configuration(auth and so on) of hex.pm
  - mkdir -p ~/.hex/
  - openssl aes-256-cbc -K $encrypted_36030c2fae51_key -iv $encrypted_36030c2fae51_iv -in hex.config.enc -out ~/.hex/hex.config -d

script:
  - mix credo --strict
  # https://github.com/jeremyjh/dialyxir#command-line-options
  # > exit immediately with same exit status as dialyzer. useful for CI
  - mix dialyzer --halt-exit-status
  - mix test
deploy:
   # https://docs.travis-ci.com/user/deployment/script/
   # > `script` must be a scalar pointing to an executable file or command.
   provider: script
   # http://yaml.org/spec/1.2/spec.html#id2779048
   # `>-` indicates the line folding.
   script: >-
     mix deps.get &&
     (echo "$HEX_PASSPHRASE"\\nY | mix hex.publish) &&
     mix clean &&
     mix deps.clean --all
   on:
    tags: true
